kind: Pod
apiVersion: v1
metadata:
  name: resources
spec: 
  containers:
  - name: nginx
    image: nginx
    resources:
    #soft limit
      requests:
        memory: "128Mi"
        cpu: "100m"
    #limits should be atleast or more than requests i.e hard limit
      limits:
        memory: "128Mi"
        cpu: "100m"