apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  # these labels belongs to replicaset resource
  labels:
    app: nginx
    tier: frontend
spec:
# modify replicas according to your need
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: frontend
  template:
    metadata:
      # these labels belongs to pod template
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
