apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-newstatic
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-013c37dc2abb7f4fa
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-newstatic
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-newstatic
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx-static
#   labels:
#     purpose: ebs-newstatic
#     project: expense
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#     volumeMounts:
#     - mountPath: /usr/share/nginx/html
#       name: persistent-storage
#   volumes:
#   - name: persistent-storage
#     persistentVolumeClaim:
#       claimName: ebs-static

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-lb
# spec:
#   type: LoadBalancer
#   selector:
#     purpose: ebs-static
#     project: expense
#   ports:
#   - port: 80
#     targetPort: 80
 
